# Generated by Django 5.0.3 on 2024-09-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_Model',
        ),
    ]
