# Generated by Django 5.0.3 on 2024-09-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_Model',
        ),
    ]
