# Generated by Django 5.0.3 on 2024-09-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_model_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_model',
            name='user_desc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
