# Generated by Django 5.0.3 on 2024-09-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_post_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_Model',
        ),
    ]
