# Generated by Django 5.0.3 on 2024-09-19 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_post_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('vid_uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
